# Generated by Django 6.0.3 on 2026-03-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_logged_in_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
