# Generated by Django 6.0.3 on 2026-03-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_user_has_logged_in_before_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('exempted', 'Exempted'), ('absent', 'Absent')], max_length=10),
        ),
    ]
