# Generated by Django 6.0.3 on 2026-03-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_unique_together_and_more'),
        ('attendance', '0003_restore_stripped_fields'),
    ]

    operations = [
    ]
