# Generated by Django 6.0.3 on 2026-03-17 09:11
# Data migration: rename 'excused' -> 'exempted' and 'unexcused' -> 'absent'

from django.db import migrations


def rename_statuses(apps, schema_editor):
    AttendanceRecord = apps.get_model('attendance', 'AttendanceRecord')
    # Update old 'excused' rows to 'exempted'
    AttendanceRecord.objects.filter(status='excused').update(status='exempted')
    # Update old 'unexcused' rows to 'absent'
    AttendanceRecord.objects.filter(status='unexcused').update(status='absent')


def revert_statuses(apps, schema_editor):
    AttendanceRecord = apps.get_model('attendance', 'AttendanceRecord')
    AttendanceRecord.objects.filter(status='exempted').update(status='excused')
    AttendanceRecord.objects.filter(status='absent').update(status='unexcused')


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.RunPython(rename_statuses, revert_statuses),
    ]
