# Generated by Django 6.0.3 on 2026-04-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_add_hierarchy_roles'),
        ('attendance', '0004_merge_20260326_0827'),
    ]

    operations = [
    ]
