# Generated by Django 6.0.3 on 2026-04-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_department_model'),
        ('attendance', '0005_merge_20260408_0908'),
    ]

    operations = [
    ]
